// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Grid$RescriptMinesweeperGame from "./Grid.bs.js";
import * as GridUI$RescriptMinesweeperGame from "./GridUI.bs.js";

import './App.css'
;

var grid = Grid$RescriptMinesweeperGame.make(9, 9, 10);

var GameLogicContext = {
  grid: grid
};

function App$AppShell(Props) {
  var children = Props.children;
  return React.createElement("section", {
              className: "AppShell"
            }, children);
}

var AppShell = {
  make: App$AppShell
};

function App(Props) {
  return React.createElement(App$AppShell, {
              children: React.createElement(GridUI$RescriptMinesweeperGame.make, {
                    cells: grid.cells
                  })
            });
}

var make = App;

export {
  GameLogicContext ,
  AppShell ,
  make ,
  
}
/*  Not a pure module */
