// Generated by ReScript, PLEASE EDIT WITH CARE


function make(hasBombOpt, state) {
  var hasBomb = hasBombOpt !== undefined ? hasBombOpt : false;
  return {
          state: state,
          hasBomb: hasBomb
        };
}

export {
  make ,
  
}
/* No side effect */
