// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";

function renderCells(cells) {
  return Belt_Array.map(cells, (function (cell) {
                var match = cell.state;
                switch (match) {
                  case /* Hidden */0 :
                      return React.createElement("div", {
                                  className: "GridCell"
                                }, "H");
                  case /* Dug */1 :
                      return React.createElement("div", {
                                  className: "GridCell"
                                }, "D");
                  case /* Blown */2 :
                      return React.createElement("div", {
                                  className: "GridCell"
                                }, "B");
                  case /* Flagged */3 :
                      return React.createElement("div", {
                                  className: "GridCell"
                                }, "F");
                  
                }
              }));
}

function GridUI(Props) {
  var cells = Props.cells;
  return React.createElement("div", {
              className: "GridUI"
            }, renderCells(cells));
}

var make = GridUI;

export {
  renderCells ,
  make ,
  
}
/* react Not a pure module */
